### PR TITLE
MavLinkDrone: Fixes #443 and makes sysid/compid use the expected shor…

### LINKED ISSUE #443: Dronekit exception sending messages to system IDs > 127
When we connect the Tower application to a Pixhawk which also has APM Planner 2 connected we see an exception in the Tower application in a call to:

`packet.payload.putUnsignedByte(target_system);`

The issue is that the system ID of APM Planner 2 is 252 and the dronekit-android throws an exception since it sees the target_system as -4 which fails the following check in putUnsignedByte() when trying to send a message to APM Planner:

`if(data < UNSIGNED_BYTE_MIN_VALUE || data > UNSIGNED_BYTE_MAX_VALUE){
    throw new IllegalArgumentException("Value is outside of the range of an unsigned byte: " + data);
}`

Presumably there shouldn't be a limit in dronekit preventing it from sending Mavlink messages to system IDs > 127?  

Regards

### PR DESCRIPTION
**Pull request by billbonney**
…t type

sysid/compid need to use short with the current library and not byte as it stores the values as an unsigned 0-255 value in the short variable. Missing the conversion will cause a crash.

This PR can serve as a discussion as to the correct fix. But I think it should be along the lines that mysid/compid needs to be represented as short (like in the library) or the java mavlink lib needs to represent unsigned bytes as signed bytes and conversion only happens when the byte is displayed to the user.

Exception is caused here

https://github.com/dronekit/dronekit-android/blob/develop/dependencyLibs/Mavlink/src/com/MAVLink/Messages/MAVLinkPayload.java#L140

When the target system id (or component id) is -127 to -1 i.e. 128-255)
https://github.com/dronekit/dronekit-android/blob/4f965d97a3dad087390a947d0669683f1895949a/dependencyLibs/Mavlink/src/com/MAVLink/common/msg_request_data_stream.java#L62

### CODE REVIEW

File: ClientLib/src/main/java/org/droidplanner/services/android/impl/core/drone/autopilot/generic/GenericMavLinkDrone.java [hunk 1]
```diff
@@ -237,13 +237,21 @@ public boolean isConnectionAlive() {
...
 
     @Override
-    public byte getCompid() {
-        return heartbeat.getCompid();
+    public short getCompid() {
+        return getUnsignedShort(heartbeat.getCompid());
+    }
+
+    // [ToDo] Helper Method that should be refactored to utility class.
+    private short getUnsignedShort(byte aByte){
```
Comment (ne0fhyk) [inline ClientLib/src/main/java/org/droidplanner/services/android/impl/core/drone/autopilot/generic/GenericMavLinkDrone.java]: @billbonney The `HeartBeat#sysid` and `HeartBeat#compid` field are coming in as `int` and being downcast to `byte`. Looks to me we should change them to short as well:
https://github.com/dronekit/dronekit-android/blob/0f1e038fb797839d5c98b041659b22ef2b2bd9bf/ClientLib/src/main/java/org/droidplanner/services/android/impl/core/drone/variables/HeartBeat.java#L67-L68

**Comment by ne0fhyk** [comment]
Fixes issue #443

**Comment by billbonney** [comment]
Interestingly it almost like  data integrity needs to be `abstract class MAVLinkMessage` to be short and in the valid 0-255 range, since at the moment these casts hide any problems. I'll think about it some more on how best to fix... (I'm almost thinking that just being real byte and only deciphering when its a to be displayed would have been more sensible) thinking some 🤔

**Comment by ne0fhyk** [comment]
@billbonney I thought about that as well, but then you'd have to decipher it everywhere you use the value, vs using a larger type everywhere, and only worry about encoding it once before you send it over the wire.

**Comment by billbonney** [comment]
I've added a slightly different fix, which validate the mysid/comid range, but really it's in the wrong place. see d25e775

The real problem is that this class https://github.com/dronekit/dronekit-android/blob/develop/dependencyLibs/Mavlink/src/com/MAVLink/Messages/MAVLinkMessage.java#L22
Should allow public access to the mysid/compid/msgid and really should have validators to make sure they are always set to be 0-255 and this problem would have been caught earlier.

As i figure the code out again, i'll see if I can fix it at source and then it should alert us to other problematic areas (if any) with casts that just don't do the right thing

File: ClientLib/src/main/java/org/droidplanner/services/android/impl/core/drone/variables/HeartBeat.java [hunk 2]
```diff
@@ -64,8 +64,8 @@ public short getMavlinkVersion() {
     public void onHeartbeat(MAVLinkMessage msg) {
         msg_heartbeat heartBeatMsg = msg instanceof msg_heartbeat ? (msg_heartbeat) msg : null;
         if(heartBeatMsg != null){
-            sysid = (byte) msg.sysid;
-            compid = (byte) msg.compid;
+            sysid  = validateToUnsignedByteRange(msg.sysid);
```
Comment (billbonney) [inline ClientLib/src/main/java/org/droidplanner/services/android/impl/core/drone/variables/HeartBeat.java]: I added this check, so that an invalid conversion would break, but since this comes over the wire it would be safe to cast from int to short. I think where the java library goes wrong is that it uses int in the first place. if it used short these issue would have shown up, as there would be no need to cast and therefore mask the problem.

**Comment by billbonney** [comment]
I've made the changes you requested. Since it now force the sys_id and comp_id to be treated as short (and it should be always to avoid problems.)

I'm not sure about adding the validate method to DroneParameter. comments welcome. thx :)

**Comment by ne0fhyk** [comment]
@billbonney I agree the fix should be made at the source, which in this case would be the mavlink `Parser` class. 
That class is autogenerated from the java mavlink library generator, so the fix needs to be applied to the original template, and the mavlink library needs to be regenerated to propagate the fix:
https://github.com/ne0fhyk/mavlink/blob/d543345a2712bb3c3f466bfddd9eef5ecf0a3d19/pymavlink/generator/java/lib/Parser.java#L64-L75

**Comment by billbonney** [comment]
@ne0fhyk The problem with the byte ranges is that they are fine for the parsing the incoming protocol ( a byte is a byte ;) ). 

After some more thought the problem was only with the container classes with sys_id/comp_id not using the 'short is a byte' convention and that was root of the error. I'll update this PR later, and i think we will be good for now with those changes

**Comment by ne0fhyk** [comment]
@billbonney sounds good. I'll merge the current pr in order to fix issue #443, and create another issue for the mavlink library for the full update.

**Comment by billbonney** [comment]
@ne0fhyk Great

I was thinking that if we do update the MAVLinkPacket object, making it so that sys_id/comp_id are set using  a setter, would allow for the check for validity to be performed easily.
